apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: angular-demo
  name: angular-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: angular-demo
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: angular-demo
    spec:
      containers:
        - image: angular-demo:latest
          name: angular-demo
          ports:
            - containerPort: 4200
              protocol: TCP
      restartPolicy: Always
