services:
  pgadmin:
    container_name: pgadmin-bd
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=angeloulloa@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "80:80"
    depends_on:
      - spring-bd
    networks:
      - mynetwork

  spring-app:
    container_name: spring-app
    image: spring-app:latest
    build: .
    ports: 
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://spring-bd:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - spring-bd
    networks:
      - mynetwork

  angular-demo:
    container_name: angular-demo
    image: angular-demo:latest
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - spring-app
    networks:
      - mynetwork

  spring-bd:
    container_name: spring-bd
    image: postgres:12
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
