apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: spring-app
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spring-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: spring-app
    spec:
      containers:
        - env:
            - name: DATABASE_PASSWORD
              value: postgres
            - name: DATABASE_URL
              value: jdbc:postgresql://spring-bd:5432/postgres
            - name: DATABASE_USERNAME
              value: postgres
          image: spring-app:latest
          name: spring-app
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
